[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
foster_studio = "fosfNb548Xe2UbMEVcrmsZWWVdxMYAuoyrxQxBvYHJj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 3000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
